// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tema/Bahar.tsx": () => import("../components/mockups/tema/Bahar.tsx"),
  "./components/mockups/tema/Doga.tsx": () => import("../components/mockups/tema/Doga.tsx"),
  "./components/mockups/tema/Kutuphane.tsx": () => import("../components/mockups/tema/Kutuphane.tsx"),
  "./components/mockups/tema/ModernBeyaz.tsx": () => import("../components/mockups/tema/ModernBeyaz.tsx")
};
