const colors = {
  light: {
    text: "#0a0a0f",
    tint: "#7c3aed",
    background: "#f8f8ff",
    foreground: "#0a0a0f",
    card: "#f0f0f8",
    cardForeground: "#0a0a0f",
    primary: "#7c3aed",
    primaryForeground: "#ffffff",
    secondary: "#06b6d4",
    secondaryForeground: "#ffffff",
    muted: "#e8e8f0",
    mutedForeground: "#6b7280",
    accent: "#7c3aed",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e0e0f0",
    input: "#e0e0f0",
  },
  dark: {
    text: "#e8e8ff",
    tint: "#7c3aed",
    background: "#080811",
    foreground: "#e8e8ff",
    card: "#0f0f1e",
    cardForeground: "#e8e8ff",
    primary: "#7c3aed",
    primaryForeground: "#ffffff",
    secondary: "#06b6d4",
    secondaryForeground: "#ffffff",
    muted: "#1a1a2e",
    mutedForeground: "#8888aa",
    accent: "#7c3aed",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e1e32",
    input: "#1e1e32",
  },
  radius: 12,
} as const;

export default colors;
